# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b270e37a965c82960b1af7924b373ba8dae4b7f0f7bf334a1801928fbede8e4547700fc95dbbc30dc738e2e2eb655511e2f4a21e33504e5f117865451ef0a68

test:
  secret_key_base: d0813fadea9b6607c82b81c3f9904238ce5166639e577ffa468b00354024066d22a81343a53a3fddac9ae5dc13c0ca137356425d48904e772a29f91c536d7dff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
